// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZtkampTpml0aLVKwlNypggS5cssAnX3I',
    appId: '1:228916444389:web:934e3a77867ee95035a80c',
    messagingSenderId: '228916444389',
    projectId: 'appgobierno-c3e76',
    authDomain: 'appgobierno-c3e76.firebaseapp.com',
    databaseURL: 'https://appgobierno-c3e76-default-rtdb.firebaseio.com',
    storageBucket: 'appgobierno-c3e76.appspot.com',
    measurementId: 'G-3SQMT9DQE9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDt2dVU4xFaH3DqNECOQGhcZP9j5hjtpg',
    appId: '1:228916444389:android:70bef0e38691a9cf35a80c',
    messagingSenderId: '228916444389',
    projectId: 'appgobierno-c3e76',
    databaseURL: 'https://appgobierno-c3e76-default-rtdb.firebaseio.com',
    storageBucket: 'appgobierno-c3e76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB55B_KS-bpJy6X_xqnTGioopqpLe9fIc',
    appId: '1:228916444389:ios:1a0ea6628e42875d35a80c',
    messagingSenderId: '228916444389',
    projectId: 'appgobierno-c3e76',
    databaseURL: 'https://appgobierno-c3e76-default-rtdb.firebaseio.com',
    storageBucket: 'appgobierno-c3e76.appspot.com',
    iosBundleId: 'com.example.directorioGrullo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB55B_KS-bpJy6X_xqnTGioopqpLe9fIc',
    appId: '1:228916444389:ios:1a0ea6628e42875d35a80c',
    messagingSenderId: '228916444389',
    projectId: 'appgobierno-c3e76',
    databaseURL: 'https://appgobierno-c3e76-default-rtdb.firebaseio.com',
    storageBucket: 'appgobierno-c3e76.appspot.com',
    iosBundleId: 'com.example.directorioGrullo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZtkampTpml0aLVKwlNypggS5cssAnX3I',
    appId: '1:228916444389:web:ee018730165c1f8c35a80c',
    messagingSenderId: '228916444389',
    projectId: 'appgobierno-c3e76',
    authDomain: 'appgobierno-c3e76.firebaseapp.com',
    databaseURL: 'https://appgobierno-c3e76-default-rtdb.firebaseio.com',
    storageBucket: 'appgobierno-c3e76.appspot.com',
    measurementId: 'G-0RL633FHXV',
  );

}